apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: flask
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  template:
    metadata:
      labels:
        io.kompose.network/dockertest-default: "true"
        io.kompose.service: flask
    spec:
      containers:
        - args:
            - python
            - app.py
          image: peacekeeper228/flask:latest
          name: flask
          ports:
            - containerPort: 5000
              protocol: TCP
          resources: 
            limits:
              memory: "512Mi"
              cpu: "250m"
      restartPolicy: Always
