version: "3"
services:
    postgres:
        image: peacekeeper228/socialpostgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        #volumes:
        #    - ./initData/:/docker-entrypoint-initdb.d/
        ports:
            - 5432:5432

    mongodb:
        image: peacekeeper228/socialmongo:latest 
        container_name: mongodb
        restart: always
        environment:
            MONGODB_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
            MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        #volumes:
        #    - ./mongodb/:/docker-entrypoint-initdb.d/:ro

    connector:
        image: peacekeeper228/apiconnector:latest
        restart: always
        environment:
            MONGO_LOGIN: ${MONGO_LOGIN}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        command: uvicorn apiconnector:app --host 0.0.0.0
        ports:
            - 8008:8000
        depends_on:
            - postgres
            - mongodb
    flask:
        image: peacekeeper228/flask:latest
        ports:
            - 80:5000
        command: python app.py
        depends_on:
            - connector