version: "3"
services:
    postgres:
        image: postgres:12.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./initData/step1_creation_tables.sql:/docker-entrypoint-initdb.d/step1_creation_tables.sql
            - ./initData/step2_filling_lookup_tables.sql:/docker-entrypoint-initdb.d/step2_filling_lookup_tables.sql
            - ./tests/data/step3_filling_test_data.sql:/docker-entrypoint-initdb.d/step3_filling_test_data.sql
            

    mongodb:
        image: mongodb/mongodb-enterprise-server:6.0.3-ubi8
        container_name: mongodb
        restart: always
        environment:
            MONGODB_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
            MONGODB_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
           - ./tests/data/mongo.js:/docker-entrypoint-initdb.d/mongo.js:ro

    connector:
        image: apiconnector:latest
        restart: always
        environment:
            MONGO_LOGIN: ${MONGO_LOGIN}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        command: uvicorn apiconnector:app --host 0.0.0.0
        ports:
            - 8008:8000
        depends_on:
            - postgres
            - mongodb
    flask:
        image: flask:latest
        ports:
            - 80:5000
        command: python app.py
        depends_on:
            - connector

    pgadmin:
        image: dpage/pgadmin4:7.1
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - 15432:80
        depends_on:
            - postgres

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_LOGIN}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017