apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: flask
  name: flask
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    io.kompose.service: flask
