apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: connector
  name: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector
  template:
    metadata:
      labels:
        io.kompose.network/dockertest-default: "true"
        io.kompose.service: connector
    spec:
      containers:
        - args:
            - uvicorn
            - apiconnector:app
            - --host
            - 0.0.0.0
          env:
            - name: MONGO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_LOGIN
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
          image: peacekeeper228/apiconnector:latest
          name: connector
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
      restartPolicy: Always
